service: dash-lambda-example

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-southeast-2
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements
#  - serverless-plugin-warmup

package:
  exclude:
    - venv/**

custom:
  pythonRequirements:
    slim: true
    zip: true
  wsgi:
    app: app.server
    packRequirements: false
#
#  warmup:
#    default:
#      - production
#        # lambdas in dev and staging environment can even freeze... who cares.
#    schedule: 'cron(0/20 8-18:30 ? * MON-FRI *)'
#        # since our API is used only from an internal company WebApp keep lambda warm only every 20 minutes in office hours.
#    prewarm: true # Run WarmUp immediately after a deployment
#    concurrency: 2 # Warm up 2 concurrent instances

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'