service: dash-lambda-example

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-southeast-2
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - venv/**

custom:
  pythonRequirements:
    slim: true
    zip: true
  wsgi:
    app: app.server
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'